id: A62B82DC3
title: 'Bright Lamp for the Profound Path: A Guru Yoga'
type: translation
pechas:
- I58BBC3C4
- I20EABAA4
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:12:07.074382
  last_modified_at: 2023-01-04 12:12:07.074388
  collections:
  - Jamyang Khyentse Chökyi Lodrö Series
  - Works of Tibetan Masters
alignment_to_base:
  I58BBC3C4/0780: 8B78
  I20EABAA4/BD6C: 8B78
